{
  "formatVersion": "1.1",
  "component": {
    "group": "com.doverunner",
    "module": "widevine",
    "version": "4.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "widevine-4.5.1.aar",
          "url": "widevine-4.5.1.aar",
          "size": 224560,
          "sha512": "d3bb46e59be0067903667adbd2719594b0a54f3721573e536cb569d1ba30cb099424cf5c20bc9f90064954c9f079a64c00a1af98d784e8f9bb3db5b05cc2fa03",
          "sha256": "45ec1426a33b0b528ad7e411369535693d2bb4a9a9a40ed2945605ebdf761d83",
          "sha1": "1a2047afbc67d4f0c3993d67bf9cb54bca36cd0e",
          "md5": "b493f23bddb056d8d7e61552dd62ce92"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-tasks",
          "version": {
            "requires": "18.3.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "widevine-4.5.1.aar",
          "url": "widevine-4.5.1.aar",
          "size": 224560,
          "sha512": "d3bb46e59be0067903667adbd2719594b0a54f3721573e536cb569d1ba30cb099424cf5c20bc9f90064954c9f079a64c00a1af98d784e8f9bb3db5b05cc2fa03",
          "sha256": "45ec1426a33b0b528ad7e411369535693d2bb4a9a9a40ed2945605ebdf761d83",
          "sha1": "1a2047afbc67d4f0c3993d67bf9cb54bca36cd0e",
          "md5": "b493f23bddb056d8d7e61552dd62ce92"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "widevine-4.5.1-sources.jar",
          "url": "widevine-4.5.1-sources.jar",
          "size": 61591,
          "sha512": "1cfb2312597de3c8e5e333a32da18363bdcc9423e69e0699117ab3e0e9a0bfc69a025f409f9c0e88fd53bd0fe71785ffd5b49c3cd29834a5fcfb92d49f2c75e0",
          "sha256": "09d731791f2d1464637c64363afb70276de77d7411a0e33aa2094cc00c5ef33d",
          "sha1": "0c8107a1e8eba8c89e8d735f70de33d3378f9b12",
          "md5": "c8e2a5fd185024d45c90a39d7cd7f3ea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "widevine-4.5.1-javadoc.jar",
          "url": "widevine-4.5.1-javadoc.jar",
          "size": 518644,
          "sha512": "52637e90679a41584ecc06b461ee73b6649d39f22a7a8bb84ba0e7d15d46f890e1473cacbbf2fd37d50e80ec202f88f89d2b9e46c916e34b93ee2691b45fde43",
          "sha256": "0915e78155bd5628686e45f665e021601ffbce22d769c21126a01a0f09af1bdc",
          "sha1": "0cd74a398a5168a0c818713bee76a1c671b60d2a",
          "md5": "476daf91d11ae5d146cd4cc344b50b59"
        }
      ]
    }
  ]
}
