{
  "formatVersion": "1.1",
  "component": {
    "group": "com.doverunner",
    "module": "widevine",
    "version": "4.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "widevine-4.5.1.aar",
          "url": "widevine-4.5.1.aar",
          "size": 224970,
          "sha512": "4c3d28a449d898c5789aac323291e4d39987a7e854b839fe46b0cef60504b86cecbbd071219c56c388fb0bee9499ecfcbbb3dc2e07e385b3f0bbe890a9a305a1",
          "sha256": "ca43dfddbdb8a8c7dfd29aa967e3b1bf3277608583c68e22d3bda35c65547ef3",
          "sha1": "79336341659bd43fa2b8907ecd13960fc7d84d4c",
          "md5": "d0ef496f2877d0b4e440f55ae8acfb4e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-tasks",
          "version": {
            "requires": "18.3.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "widevine-4.5.1.aar",
          "url": "widevine-4.5.1.aar",
          "size": 224970,
          "sha512": "4c3d28a449d898c5789aac323291e4d39987a7e854b839fe46b0cef60504b86cecbbd071219c56c388fb0bee9499ecfcbbb3dc2e07e385b3f0bbe890a9a305a1",
          "sha256": "ca43dfddbdb8a8c7dfd29aa967e3b1bf3277608583c68e22d3bda35c65547ef3",
          "sha1": "79336341659bd43fa2b8907ecd13960fc7d84d4c",
          "md5": "d0ef496f2877d0b4e440f55ae8acfb4e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "widevine-4.5.1-sources.jar",
          "url": "widevine-4.5.1-sources.jar",
          "size": 184486,
          "sha512": "8a0c9f6cae79610564f79479518e72d6f207b6e3560cc44ea3d7893de50ec5be6ce366db851fb8a80a960a11dfdc1579bca5aaa238bfe7b965bbf011e29bc2eb",
          "sha256": "b2c7c21daefff72af138d5fa4c9538b2ad9208bbfbdc3f1078778a9a6c12786a",
          "sha1": "c089c20162104b96ff8e1cd8be2b5b053815b9b1",
          "md5": "537455dace28494b8dd1c67d525d072a"
        }
      ]
    }
  ]
}
