{
  "formatVersion": "1.1",
  "component": {
    "group": "com.doverunner",
    "module": "widevine",
    "version": "4.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "widevine-4.5.3.aar",
          "url": "widevine-4.5.3.aar",
          "size": 225003,
          "sha512": "0b2fc17c3e02a2e11dd3afbadf1fa460522aa1f43fb9c1bbae07a2498d2c87c1c91506813e136771e1ba5b93f97b4f259a0a6d6a8dbb3976e2feb3d642b7f22f",
          "sha256": "3cd905e87a251a0caba55088b49d08128951c183cc942df6a1590bdb3e0fe721",
          "sha1": "09f67b6921a24b9e5032875892a9a8686152c31c",
          "md5": "a7375799eb8bb343b84c2e5fbfcb7e11"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-tasks",
          "version": {
            "requires": "18.3.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "widevine-4.5.3.aar",
          "url": "widevine-4.5.3.aar",
          "size": 225003,
          "sha512": "0b2fc17c3e02a2e11dd3afbadf1fa460522aa1f43fb9c1bbae07a2498d2c87c1c91506813e136771e1ba5b93f97b4f259a0a6d6a8dbb3976e2feb3d642b7f22f",
          "sha256": "3cd905e87a251a0caba55088b49d08128951c183cc942df6a1590bdb3e0fe721",
          "sha1": "09f67b6921a24b9e5032875892a9a8686152c31c",
          "md5": "a7375799eb8bb343b84c2e5fbfcb7e11"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "widevine-4.5.3-sources.jar",
          "url": "widevine-4.5.3-sources.jar",
          "size": 62017,
          "sha512": "41a053c633ef5337bc1b78bb6ea395c4ea432e3c2ac3c2b2bcb51f4179d193001ce563e44f99414ecb5a88869d697b6e3ee5b6addc6a2f58d03f7edc5f67ad82",
          "sha256": "66a78cf8d4bf3e0993daea2cf1d2a57a6cb05dcbc4fc3f573cd2ae733d230fa3",
          "sha1": "e8f9db67df5cecd09bb4c5baab9895b4f5ed4ca9",
          "md5": "efe9fad458661f06998785253cc493d5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "widevine-4.5.3-javadoc.jar",
          "url": "widevine-4.5.3-javadoc.jar",
          "size": 518635,
          "sha512": "7289abca3ae6f2186c206e32d17ae55424f12299450bb570e260de09ba57de77a290276af59c1c7e274411434a74528159ca7b0edef40294adc2886a7c37f624",
          "sha256": "96c4f9774341743ed21574326695d607a917bcf07f86cb879de4af4a07fb91a0",
          "sha1": "8a1d367e74beed528069b17d7cad3aba16954c5e",
          "md5": "589447f45a440909e901198f6cc9ba5c"
        }
      ]
    }
  ]
}
