{
  "formatVersion": "1.1",
  "component": {
    "group": "com.doverunner",
    "module": "widevine",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "widevine-4.4.0.aar",
          "url": "widevine-4.4.0.aar",
          "size": 177622,
          "sha512": "8be74bed4e1252f2b66d9fe74e89bc467d0cfa89ee1ccdc93e42dd1deaa1cf701280a3e86016f45851cf499d8ae76893c282685ea73de064886df54e08b1c301",
          "sha256": "a5e84b8b87258e8a821485b0ef85ed89ce211a18aeb4c57414b94941bcda5532",
          "sha1": "fe12accbd1923d97108f275134463c511ca7bd69",
          "md5": "6cfc2ace8ae7a09aaf0a7a111efa4781"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto-ktx",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "widevine-4.4.0.aar",
          "url": "widevine-4.4.0.aar",
          "size": 177622,
          "sha512": "8be74bed4e1252f2b66d9fe74e89bc467d0cfa89ee1ccdc93e42dd1deaa1cf701280a3e86016f45851cf499d8ae76893c282685ea73de064886df54e08b1c301",
          "sha256": "a5e84b8b87258e8a821485b0ef85ed89ce211a18aeb4c57414b94941bcda5532",
          "sha1": "fe12accbd1923d97108f275134463c511ca7bd69",
          "md5": "6cfc2ace8ae7a09aaf0a7a111efa4781"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "widevine-4.4.0-sources.jar",
          "url": "widevine-4.4.0-sources.jar",
          "size": 50266,
          "sha512": "a07cecf26475651d36a55526f0d2337c28a437f9c509f65eb827b342421bf8cbb65857d6ca8d3a1440df1ca3186c0d59eb79bd38b937ffe49a1b7917d2edf2d9",
          "sha256": "d4ff0e46fb46b97b8f383a1455af74ab1ed07557ed0f0dd792f0098f15e205b2",
          "sha1": "4897e2d8c1b1e80334f0d3bf320b9a1a3f889bbc",
          "md5": "7b19ea83d0ca5e978b6611afd60dcc5a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "widevine-4.4.0-javadoc.jar",
          "url": "widevine-4.4.0-javadoc.jar",
          "size": 478078,
          "sha512": "7d53d1826b602e0e81c5b586154eaf40fe7985dcc32e68836843f0efe26147f2ad8003e20f3a022565049c19deb3c47ff1919ce53bec80cf33a16705b0d59e19",
          "sha256": "942bff79d0b9320e5b559840acf892920aae5aea8811837608892b819f96adf4",
          "sha1": "c52ff2cf7a32290704c011fdf43c6528239526df",
          "md5": "4f6b1c14381f7a158103cf840691185b"
        }
      ]
    }
  ]
}
