{
  "formatVersion": "1.1",
  "component": {
    "group": "com.doverunner",
    "module": "widevine",
    "version": "4.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "widevine-4.5.0.aar",
          "url": "widevine-4.5.0.aar",
          "size": 225517,
          "sha512": "db6f14d3115c93f07a52f2532aa89b35dfbd945e8aba583e8b45b7997bc1e2391ae0340979f9bb1dabbbc0960c5541cc2027a43012e1a17e6edfc97b46ecee78",
          "sha256": "6179d9f82b24643f47a395614755cf62a3623299a03df5d00803ac8c91ee51f6",
          "sha1": "94ddfa7fca0b66e5b57122e9bdb8891e25529bc8",
          "md5": "dfb6cb8dc4ae58adfad88437d18996f1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-tasks",
          "version": {
            "requires": "18.3.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "widevine-4.5.0.aar",
          "url": "widevine-4.5.0.aar",
          "size": 225517,
          "sha512": "db6f14d3115c93f07a52f2532aa89b35dfbd945e8aba583e8b45b7997bc1e2391ae0340979f9bb1dabbbc0960c5541cc2027a43012e1a17e6edfc97b46ecee78",
          "sha256": "6179d9f82b24643f47a395614755cf62a3623299a03df5d00803ac8c91ee51f6",
          "sha1": "94ddfa7fca0b66e5b57122e9bdb8891e25529bc8",
          "md5": "dfb6cb8dc4ae58adfad88437d18996f1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "widevine-4.5.0-sources.jar",
          "url": "widevine-4.5.0-sources.jar",
          "size": 183538,
          "sha512": "5f8df2ec2f434abfc4900746cffc97ba09e122af426a1178760f3c87251786bf28ad51ed0b69ccec21ce6d76d6f53d9e367a3eedfcca4c0ffb932f10b0729145",
          "sha256": "90284274adc2efe5d99282976795b3232e7fddcf54a7a1cf21febb3e25e04191",
          "sha1": "6ca5925e84ab487f3a1c8eb334fc212dfb06d807",
          "md5": "142de8466a75d0496ded6226ce82062f"
        }
      ]
    }
  ]
}
