{
  "formatVersion": "1.1",
  "component": {
    "group": "com.doverunner",
    "module": "widevine",
    "version": "4.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "widevine-4.5.0.aar",
          "url": "widevine-4.5.0.aar",
          "size": 224584,
          "sha512": "679cd61c831f185b8fa784ca3324ec497623ae901a784842c8c0ff92a921889f84a168b3cfe14f14d7bcdbda8f9e27ec88e273e8325c13d8959b54f65aafd101",
          "sha256": "46c624400cf5f574c43b3ed9fe9aa267c7f5ebbac7d3bd9c6dcfe939e157a1af",
          "sha1": "9630574afef044ecea0bdda65aa6083f16b10edc",
          "md5": "84a31f488fbe82d46fa6995dfc56e64a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-tasks",
          "version": {
            "requires": "18.3.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "widevine-4.5.0.aar",
          "url": "widevine-4.5.0.aar",
          "size": 224584,
          "sha512": "679cd61c831f185b8fa784ca3324ec497623ae901a784842c8c0ff92a921889f84a168b3cfe14f14d7bcdbda8f9e27ec88e273e8325c13d8959b54f65aafd101",
          "sha256": "46c624400cf5f574c43b3ed9fe9aa267c7f5ebbac7d3bd9c6dcfe939e157a1af",
          "sha1": "9630574afef044ecea0bdda65aa6083f16b10edc",
          "md5": "84a31f488fbe82d46fa6995dfc56e64a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "widevine-4.5.0-sources.jar",
          "url": "widevine-4.5.0-sources.jar",
          "size": 183496,
          "sha512": "8845399e59a3898a19076456f0eb0ac5bfec3e890555e144d76bc93a0398f49d947858c898a9aed45bb462bc89a0edba5e08b5b95e7648136505fd6599e5182f",
          "sha256": "5c92741bc1719098898841adc1b9894d9aaa7039ad1355518f77da96b6f0b035",
          "sha1": "ef2d1cbaa59f588ad47c0e171561f426538f94e0",
          "md5": "e43f021e0cb1cbff25e6c01fe3366c00"
        }
      ]
    }
  ]
}
